-- SolarPower WhatsApp Agent on Supabase.
-- All application-owned objects use the agent_ / agent- prefix so this can
-- coexist with the existing SolarPower platform without modifying its tables.

create extension if not exists pg_cron;
create extension if not exists pg_net;

create table if not exists public.agent_contacts (
  phone text primary key,
  legacy_id bigint unique,
  name text,
  email text,
  label text not null default 'Interesado',
  stage text not null default 'nuevo',
  tipo text,
  otro_count integer not null default 0,
  bill_received boolean not null default false,
  roof_type text,
  connection_type text,
  locality text,
  product_interest text,
  notes text,
  notified_ricardo boolean not null default false,
  human_mode boolean not null default false,
  first_contact timestamptz not null default now(),
  last_contact timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.agent_messages (
  id bigint generated by default as identity primary key,
  legacy_id bigint unique,
  contact_phone text not null references public.agent_contacts(phone) on update cascade on delete restrict,
  role text not null check (role in ('user', 'assistant', 'system')),
  content text not null,
  provider_message_id text unique,
  model text,
  created_at timestamptz not null default now()
);

create table if not exists public.agent_pending_actions (
  id bigint generated by default as identity primary key,
  legacy_id bigint unique,
  contact_phone text not null,
  action_type text not null,
  description text,
  resolved boolean not null default false,
  created_at timestamptz not null default now(),
  resolved_at timestamptz
);

create table if not exists public.agent_agenda_events (
  id bigint generated by default as identity primary key,
  legacy_id bigint unique,
  google_event_id text,
  title text not null,
  description text,
  date_time timestamptz not null,
  duration_minutes integer not null default 60 check (duration_minutes > 0),
  location text,
  event_type text not null default 'reunion',
  contact_name text,
  contact_phone text,
  attendee_emails text,
  status text not null default 'pendiente',
  reminder_sent boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.agent_agenda_messages (
  id bigint generated by default as identity primary key,
  legacy_id bigint unique,
  role text not null check (role in ('user', 'assistant', 'system')),
  content text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.agent_pending_notifications (
  id bigint generated by default as identity primary key,
  legacy_id bigint unique,
  phone text not null,
  message text not null,
  sent boolean not null default false,
  created_at timestamptz not null default now(),
  sent_at timestamptz,
  last_error text
);

create table if not exists public.agent_conversation_logs (
  id bigint generated by default as identity primary key,
  legacy_id bigint unique,
  contact_phone text not null,
  event_type text not null,
  label text,
  summary text not null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.agent_inbound_events (
  id uuid primary key default gen_random_uuid(),
  provider_message_id text unique,
  phone text not null,
  contact_name text,
  message_type text not null default 'text',
  content text,
  media_id text,
  media_mime_type text,
  raw_payload jsonb not null default '{}'::jsonb,
  received_at timestamptz not null default now(),
  processed_at timestamptz,
  processing_error text
);

create table if not exists public.agent_jobs (
  id uuid primary key default gen_random_uuid(),
  dedupe_key text unique,
  job_type text not null,
  payload jsonb not null default '{}'::jsonb,
  status text not null default 'pending' check (status in ('pending', 'processing', 'completed', 'failed')),
  attempts integer not null default 0,
  available_at timestamptz not null default now(),
  locked_at timestamptz,
  completed_at timestamptz,
  last_error text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.agent_outbound_messages (
  id bigint generated by default as identity primary key,
  phone text not null,
  content text not null,
  message_type text not null default 'text',
  provider_message_id text,
  status text not null default 'pending',
  error text,
  created_at timestamptz not null default now(),
  sent_at timestamptz
);

create table if not exists public.agent_files (
  id uuid primary key default gen_random_uuid(),
  contact_phone text not null,
  inbound_event_id uuid references public.agent_inbound_events(id) on delete set null,
  storage_path text not null unique,
  file_name text,
  mime_type text,
  provider_media_id text,
  analysis text,
  created_at timestamptz not null default now()
);

create table if not exists public.agent_settings (
  key text primary key,
  value text not null,
  is_secret boolean not null default false,
  updated_at timestamptz not null default now()
);

insert into public.agent_settings (key, value, is_secret)
values
  ('bot_enabled', 'false', false),
  ('cron_secret', encode(gen_random_bytes(32), 'hex'), true),
  ('migration_status', 'schema_ready', false)
on conflict (key) do nothing;

create or replace function public.agent_touch_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

revoke all on function public.agent_touch_updated_at() from public, anon, authenticated;
grant execute on function public.agent_touch_updated_at() to service_role;

create trigger agent_contacts_updated_at before update on public.agent_contacts
for each row execute function public.agent_touch_updated_at();

create trigger agent_agenda_events_updated_at before update on public.agent_agenda_events
for each row execute function public.agent_touch_updated_at();

create trigger agent_jobs_updated_at before update on public.agent_jobs
for each row execute function public.agent_touch_updated_at();

create index if not exists agent_messages_phone_created_idx on public.agent_messages(contact_phone, created_at desc);
create index if not exists agent_actions_open_idx on public.agent_pending_actions(resolved, created_at desc);
create index if not exists agent_agenda_due_idx on public.agent_agenda_events(status, reminder_sent, date_time);
create index if not exists agent_inbound_pending_idx on public.agent_inbound_events(phone, processed_at, received_at);
create index if not exists agent_jobs_due_idx on public.agent_jobs(status, available_at);
create index if not exists agent_outbound_status_idx on public.agent_outbound_messages(status, created_at);

alter table public.agent_contacts enable row level security;
alter table public.agent_messages enable row level security;
alter table public.agent_pending_actions enable row level security;
alter table public.agent_agenda_events enable row level security;
alter table public.agent_agenda_messages enable row level security;
alter table public.agent_pending_notifications enable row level security;
alter table public.agent_conversation_logs enable row level security;
alter table public.agent_inbound_events enable row level security;
alter table public.agent_jobs enable row level security;
alter table public.agent_outbound_messages enable row level security;
alter table public.agent_files enable row level security;
alter table public.agent_settings enable row level security;

revoke all on table public.agent_contacts, public.agent_messages, public.agent_pending_actions,
  public.agent_agenda_events, public.agent_agenda_messages, public.agent_pending_notifications,
  public.agent_conversation_logs, public.agent_inbound_events, public.agent_jobs,
  public.agent_outbound_messages, public.agent_files, public.agent_settings from anon, authenticated;

grant all on table public.agent_contacts, public.agent_messages, public.agent_pending_actions,
  public.agent_agenda_events, public.agent_agenda_messages, public.agent_pending_notifications,
  public.agent_conversation_logs, public.agent_inbound_events, public.agent_jobs,
  public.agent_outbound_messages, public.agent_files, public.agent_settings to service_role;
grant usage, select on sequence public.agent_messages_id_seq,
  public.agent_pending_actions_id_seq, public.agent_agenda_events_id_seq,
  public.agent_agenda_messages_id_seq, public.agent_pending_notifications_id_seq,
  public.agent_conversation_logs_id_seq, public.agent_outbound_messages_id_seq to service_role;

insert into storage.buckets (id, name, public, file_size_limit)
values ('agent-files', 'agent-files', false, 20971520)
on conflict (id) do nothing;

select cron.schedule(
  'agent-process-every-minute',
  '* * * * *',
  $agent_cron$
  select net.http_post(
    url := 'https://ddocohkgabfhsolfarvr.supabase.co/functions/v1/agent-cron',
    headers := jsonb_build_object(
      'Content-Type', 'application/json',
      'x-agent-cron-secret', (select value from public.agent_settings where key = 'cron_secret')
    ),
    body := jsonb_build_object('scheduled_at', now()),
    timeout_milliseconds := 10000
  );
  $agent_cron$
);
